name: CI
on: 
  pull_request:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - run: npm run format
      - run: npm run format-check
      - run: npm test -- --coverage
        env:
          CI: true
      
